// Bundles /shader/webgpu/**/*.wgsl into src/tensor/webgpu/shaders.ts
//
// The WebGPU specification only accepts WGSL source code as the shader module
// input, so the shaders are embedded as strings.

const fs = require('fs');
const path = require('path');

const packageRoot = path.dirname(__dirname);
const sourcesDir = path.join(packageRoot, 'shader/webgpu');
const dstPath = path.join(packageRoot, 'src/tensor/webgpu/shaders.ts');

// recursively search *.wgsl in this directory
const namePattern = /^.*\.wgsl$/;
const allFiles = [];
const appendFilesInDirectory = (dir) => {
  const files = fs.readdirSync(dir).sort();
  files.forEach((file) => {
    const p = path.join(dir, file);
    const stat = fs.statSync(p);
    if (stat.isDirectory()) {
      appendFilesInDirectory(p);
    } else if (stat.isFile() && namePattern.test(file)) {
      allFiles.push(p);
    }
  });
};
appendFilesInDirectory(sourcesDir);

// shader name = basename of file
const entries = new Map();
allFiles.forEach((file) => {
  const basename = path.basename(file, '.wgsl');
  const found = entries.get(basename);
  if (found) {
    throw new Error(
      `Duplicated shader name '${basename}': ${found.file} and ${file}`
    );
  }
  entries.set(basename, {
    file,
    source: fs.readFileSync(file, { encoding: 'utf-8' }),
  });
});

const escapeTemplateLiteral = (source) =>
  source.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

let output =
  '// Auto-generated by tools/compile_webgpu_shader.js. Do not edit.\n\n' +
  'export const webgpuShaders: { [index: string]: string } = {\n';
for (const [name, { source }] of entries) {
  output += `  ${JSON.stringify(name)}: \`${escapeTemplateLiteral(source)}\`,\n`;
}
output += '};\n';

fs.writeFileSync(dstPath, output);
console.log(`${entries.size} shaders written to ${dstPath}`);
