# Generates shader/webgpu/autogen/strided_copy_*.wgsl

import os

package_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
dst_dir = os.path.join(package_root, "shader/webgpu/autogen")
os.makedirs(dst_dir, exist_ok=True)


DTYPE_TO_SCALAR_TYPE = {
    "float32": "f32",
    "int32": "i32",
    "uint8": "u32",
    "bool": "u32",
}


def generateMetaMembers(dim) -> str:
    members = ["  len: u32,"]
    for prefix in ["outShape", "xStride"]:
        for d in range(dim):
            members.append(f"  {prefix}{d}: u32,")
    return "\n".join(members)


def generateMetaLoads(dim) -> str:
    lines = []
    for prefix in ["outShape", "xStride"]:
        for d in range(dim):
            lines.append(f"  let {prefix}{d} = metaBuffer.{prefix}{d};")
    return "\n".join(lines)


def generateDecomposeDim(dim) -> str:
    lines = ["    var dec_tmp = i;"]
    for d in range(dim - 1, -1, -1):
        lines.append(f"    let dim{d} = dec_tmp % outShape{d};")
        if d > 0:
            lines.append(f"    dec_tmp = dec_tmp / outShape{d};")
    return "\n".join(lines)


for t in ["float32", "int32", "uint8", "bool"]:
    scalar_type = DTYPE_TO_SCALAR_TYPE[t]
    for dim in range(8):
        kernel_name = f"strided_copy_{t}_{dim}"

        if dim > 0:
            x_index = "+".join([f"dim{d} * xStride{d}" for d in range(dim)])
            body = f"""{generateDecomposeDim(dim)}

    let v = array_x[{x_index}];
    array_y[i] = v;"""
        else:
            body = """    let v = array_x[0];
    array_y[i] = v;"""

        source = f"""// Auto-generated by tools/generate_webgputensor_wgsl_copy_op.py

@group(0) @binding(0) var<storage, read> array_x: array<{scalar_type}>;
@group(0) @binding(1) var<storage, read_write> array_y: array<{scalar_type}>;

struct MetaBuffer {{
{generateMetaMembers(dim)}
}}

@group(0) @binding(2) var<storage, read> metaBuffer: MetaBuffer;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {{
  let len = metaBuffer.len;
{generateMetaLoads(dim)}
  for (var i = global_id.x; i < len; i = i + 4096u) {{
{body}
  }}
}}
"""
        with open(os.path.join(dst_dir, kernel_name + ".wgsl"), "w") as f:
            f.write(source)
