# Generates shader/webgpu/autogen/unary_*.wgsl

import os

package_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
dst_dir = os.path.join(package_root, "shader/webgpu/autogen")
os.makedirs(dst_dir, exist_ok=True)

op_template = """// Auto-generated by tools/generate_webgputensor_wgsl_unary_op.py

@group(0) @binding(0) var<storage, read> array_a: array<%%SCALAR_TYPE%%>;
@group(0) @binding(1) var<storage, read_write> array_b: array<%%SCALAR_TYPE%%>;

struct MetaBuffer {
  len: u32,
}

@group(0) @binding(2) var<storage, read> metaBuffer: MetaBuffer;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {
  let len = metaBuffer.len;
  for (var i = global_id.x; i < len; i = i + 4096u) {
    let v = array_a[i];
    array_b[i] = %%OP%%;
  }
}
"""

DTYPE_TO_SCALAR_TYPE = {
    "float32": "f32",
    "int32": "i32",
    "uint8": "u32",
    "bool": "u32",
}

D_F = ["float32"]
D_FI = ["float32", "int32"]
D_A = ["float32", "int32", "uint8", "bool"]

# WGSL has no ternary operator; select(false_value, true_value, condition) is used instead.
# tanh() overflows to NaN for large inputs in some implementations, so the numerically
# stable form is used, matching the WebGL backend (see webgl/core/unary.ts).
for name, op, supported_types in sorted([
    ["copy", "v", D_A],
    ["exp", "exp(v)", D_F],
    ["neg", "-v", D_FI],
    ["square", "v * v", D_FI],
    ["sqrt", "sqrt(v)", D_F],
    ["log", "log(v)", D_F],
    ["abs", "abs(v)", D_FI],
    ["acos", "acos(v)", D_F],
    ["acosh", "acosh(v)", D_F],
    ["asin", "asin(v)", D_F],
    ["asinh", "asinh(v)", D_F],
    ["atan", "atan(v)", D_F],
    ["atanh", "atanh(v)", D_F],
    ["cos", "cos(v)", D_F],
    ["cosh", "cosh(v)", D_F],
    ["sin", "sin(v)", D_F],
    ["sinh", "sinh(v)", D_F],
    ["tan", "tan(v)", D_F],
    ["tanh", "((1.0 - exp(-2.0 * abs(v))) / (1.0 + exp(-2.0 * abs(v))) * sign(v))", D_F],
    ["relu", "select(0.0, v, v > 0.0)", D_F],
    ["sigmoid", "1.0 / (1.0 + exp(-v))", D_F],
]):
    for t in supported_types:
        kernel_name = f"unary_{name}_{t}"
        source = op_template.replace(
            "%%SCALAR_TYPE%%", DTYPE_TO_SCALAR_TYPE[t]).replace("%%OP%%", op)
        with open(os.path.join(dst_dir, kernel_name + ".wgsl"), "w") as f:
            f.write(source)
