# Generates shader/webgpu/autogen/binary_*.wgsl

import os

package_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
dst_dir = os.path.join(package_root, "shader/webgpu/autogen")
os.makedirs(dst_dir, exist_ok=True)


DTYPE_TO_SCALAR_TYPE = {
    "float32": "f32",
    "int32": "i32",
    "uint8": "u32",
    "bool": "u32",
}

D_F = ["float32"]
D_FI = ["float32", "int32"]
D_FIU = ["float32", "int32", "uint8"]
D_A = ["float32", "int32", "uint8", "bool"]


def generateMetaMembers(dim) -> str:
    members = ["  len: u32,"]
    for prefix in ["outShape", "lhsStride", "rhsStride"]:
        for d in range(dim):
            members.append(f"  {prefix}{d}: u32,")
    return "\n".join(members)


def generateMetaLoads(dim) -> str:
    lines = []
    for prefix in ["outShape", "lhsStride", "rhsStride"]:
        for d in range(dim):
            lines.append(
                f"  let {prefix}{d} = metaBuffer.{prefix}{d};")
    return "\n".join(lines)


def generateDecomposeDim(dim) -> str:
    lines = ["    var dec_tmp = i;"]
    for d in range(dim - 1, -1, -1):
        lines.append(f"    let dim{d} = dec_tmp % outShape{d};")
        if d > 0:
            lines.append(f"    dec_tmp = dec_tmp / outShape{d};")
    return "\n".join(lines)


# about pow
# pow(-1.5, 2) causes an error in GLSL/WGSL, but it is useful in normalization
# algorithms. implementation: pow(abs(-1.5), 2)
#
# WGSL has no ternary operator; select(false_value, true_value, condition) is used.
for name, op_template, supported_types in sorted([
    ["add", "lhs + rhs", D_FIU],
    ["minimum", "min(lhs, rhs)", D_FIU],
    ["maximum", "max(lhs, rhs)", D_FIU],
    # {s}はスカラー型に置換される。boolからの変換で0/1になる。
    ["equal", "{s}(lhs == rhs)", D_FIU],
    ["sub", "lhs - rhs", D_FIU],
    ["mul", "lhs * rhs", D_FIU],
    ["div", "lhs / rhs", D_FIU],
    ["pow", "pow(abs(lhs), rhs)", D_F],
    ["sigmoidBackprop", "(1.0 - lhs) * lhs * rhs", D_F],
    # webgpu/core/binary.ts exposes tanhBackprop, but the shader was missing.
    # The formula matches the CPU and WebGL backends.
    ["tanhBackprop", "(1.0 - lhs * lhs) * rhs", D_F],
    ["reluBackprop", "select(0.0, rhs, lhs > 0.0)", D_F],
]):
    for t in supported_types:
        scalar_type = DTYPE_TO_SCALAR_TYPE[t]
        op = op_template.replace("{s}", scalar_type)
        for dim in range(8):
            kernel_name = f"binary_{name}_{t}_{dim}"

            if dim > 0:
                lhs_index = "+".join(
                    [f"dim{d} * lhsStride{d}" for d in range(dim)])
                rhs_index = "+".join(
                    [f"dim{d} * rhsStride{d}" for d in range(dim)])
                body = f"""{generateDecomposeDim(dim)}

    let lhs = array_lhs[{lhs_index}];
    let rhs = array_rhs[{rhs_index}];
    array_c[i] = {op};"""
            else:
                body = f"""    let lhs = array_lhs[0];
    let rhs = array_rhs[0];
    array_c[i] = {op};"""

            source = f"""// Auto-generated by tools/generate_webgputensor_wgsl_binary_op.py

@group(0) @binding(0) var<storage, read> array_lhs: array<{scalar_type}>;
@group(0) @binding(1) var<storage, read> array_rhs: array<{scalar_type}>;
@group(0) @binding(2) var<storage, read_write> array_c: array<{scalar_type}>;

struct MetaBuffer {{
{generateMetaMembers(dim)}
}}

@group(0) @binding(3) var<storage, read> metaBuffer: MetaBuffer;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {{
  let len = metaBuffer.len;
{generateMetaLoads(dim)}
  for (var i = global_id.x; i < len; i = i + 4096u) {{
{body}
  }}
}}
"""
            with open(os.path.join(dst_dir, kernel_name + ".wgsl"), "w") as f:
                f.write(source)
