# Generates shader/webgpu/autogen/tri_*.wgsl (tril / triu)

import os

package_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
dst_dir = os.path.join(package_root, "shader/webgpu/autogen")
os.makedirs(dst_dir, exist_ok=True)

DTYPE_TO_SCALAR_TYPE = {
    "float32": "f32",
    "int32": "i32",
    "uint8": "u32",
    "bool": "u32",
}

# signは1でtril、-1でtriu。対角線から外れた側を0にする。
TEMPLATE = """// Auto-generated by tools/generate_webgputensor_wgsl_tri_op.py

@group(0) @binding(0) var<storage, read> array_x: array<%%SCALAR_TYPE%%>;
@group(0) @binding(1) var<storage, read_write> array_y: array<%%SCALAR_TYPE%%>;

struct MetaBuffer {
  len: u32,
  shape1: u32,
  diagonal: i32,
  sign: i32,
}

@group(0) @binding(2) var<storage, read> metaBuffer: MetaBuffer;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {
  let len = metaBuffer.len;
  let shape1 = metaBuffer.shape1;
  let diagonal = metaBuffer.diagonal;
  let sign = metaBuffer.sign;
  for (var i = global_id.x; i < len; i = i + 4096u) {
    let col = i32(i % shape1);
    let row = i32(i / shape1);
    var v = %%SCALAR_TYPE%%(0);
    if ((col - row - diagonal) * sign <= 0) {
      v = array_x[i];
    }
    array_y[i] = v;
  }
}
"""

for t, scalar_type in DTYPE_TO_SCALAR_TYPE.items():
    source = TEMPLATE.replace("%%SCALAR_TYPE%%", scalar_type)
    with open(os.path.join(dst_dir, f"tri_{t}.wgsl"), "w") as f:
        f.write(source)
