# Generates shader/webgpu/autogen/strided_copy_*.wgsl and strided_set_*.wgsl
#
# strided_copy gathers: it walks the output element by element and reads the
# source at srcOffset + sum(dim_d * xStride_d).
# strided_set scatters: it walks the source element by element and writes to
# the destination at dstOffset + sum(dim_d * yStride_d). This is used by cat(),
# where several kernel launches each fill a different region of one output.

import os

package_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
dst_dir = os.path.join(package_root, "shader/webgpu/autogen")
os.makedirs(dst_dir, exist_ok=True)


DTYPE_TO_SCALAR_TYPE = {
    "float32": "f32",
    "int32": "i32",
    "uint8": "u32",
    "bool": "u32",
}

TEMPLATE = """// Auto-generated by tools/generate_webgputensor_wgsl_copy_op.py

@group(0) @binding(0) var<storage, read> array_x: array<%%SCALAR_TYPE%%>;
@group(0) @binding(1) var<storage, read_write> array_y: array<%%SCALAR_TYPE%%>;

struct MetaBuffer {
%%META_MEMBERS%%
}

@group(0) @binding(2) var<storage, read> metaBuffer: MetaBuffer;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {
  let len = metaBuffer.len;
%%META_LOADS%%
  for (var i = global_id.x; i < len; i = i + 4096u) {
%%BODY%%
  }
}
"""


def generateMetaMembers(dim, offsetName, shapeName, strideName) -> str:
    members = ["  len: u32,", f"  {offsetName}: u32,"]
    for prefix in [shapeName, strideName]:
        for d in range(dim):
            members.append(f"  {prefix}{d}: u32,")
    return "\n".join(members)


def generateMetaLoads(dim, offsetName, shapeName, strideName) -> str:
    lines = [f"  let {offsetName} = metaBuffer.{offsetName};"]
    for prefix in [shapeName, strideName]:
        for d in range(dim):
            lines.append(f"  let {prefix}{d} = metaBuffer.{prefix}{d};")
    return "\n".join(lines)


def generateDecomposeDim(dim, shapeName) -> str:
    lines = ["    var dec_tmp = i;"]
    for d in range(dim - 1, -1, -1):
        lines.append(f"    let dim{d} = dec_tmp % {shapeName}{d};")
        if d > 0:
            lines.append(f"    dec_tmp = dec_tmp / {shapeName}{d};")
    return "\n".join(lines)


def render(scalar_type, meta_members, meta_loads, body) -> str:
    return (
        TEMPLATE.replace("%%SCALAR_TYPE%%", scalar_type)
        .replace("%%META_MEMBERS%%", meta_members)
        .replace("%%META_LOADS%%", meta_loads)
        .replace("%%BODY%%", body)
    )


for t in ["float32", "int32", "uint8", "bool"]:
    scalar_type = DTYPE_TO_SCALAR_TYPE[t]
    for dim in range(8):
        # gather
        if dim > 0:
            x_index = "+".join([f"dim{d} * xStride{d}" for d in range(dim)])
            body = f"""{generateDecomposeDim(dim, "outShape")}

    array_y[i] = array_x[srcOffset + {x_index}];"""
        else:
            body = "    array_y[i] = array_x[srcOffset];"
        source = render(
            scalar_type,
            generateMetaMembers(dim, "srcOffset", "outShape", "xStride"),
            generateMetaLoads(dim, "srcOffset", "outShape", "xStride"),
            body,
        )
        with open(os.path.join(dst_dir, f"strided_copy_{t}_{dim}.wgsl"), "w") as f:
            f.write(source)

        # scatter
        if dim > 0:
            y_index = "+".join([f"dim{d} * yStride{d}" for d in range(dim)])
            body = f"""{generateDecomposeDim(dim, "srcShape")}

    array_y[dstOffset + {y_index}] = array_x[i];"""
        else:
            body = "    array_y[dstOffset] = array_x[i];"
        source = render(
            scalar_type,
            generateMetaMembers(dim, "dstOffset", "srcShape", "yStride"),
            generateMetaLoads(dim, "dstOffset", "srcShape", "yStride"),
            body,
        )
        with open(os.path.join(dst_dir, f"strided_set_{t}_{dim}.wgsl"), "w") as f:
            f.write(source)
