# Generates shader/webgpu/autogen/sum_*.wgsl

import os

package_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
dst_dir = os.path.join(package_root, "shader/webgpu/autogen")
os.makedirs(dst_dir, exist_ok=True)


DTYPE_TO_SCALAR_TYPE = {
    "float32": "f32",
    "int32": "i32",
    "uint8": "u32",
    "bool": "u32",
}


def generateMetaMembers(toDim, redDim) -> str:
    members = ["  len: u32,"]
    for prefix, dim in [
        ("toShape", toDim),
        ("toShapeStrides", toDim),
        ("reductionShape", redDim),
        ("reductionShapeStrides", redDim),
    ]:
        for d in range(dim):
            members.append(f"  {prefix}{d}: u32,")
    return "\n".join(members)


def generateMetaLoads(toDim, redDim) -> str:
    lines = []
    for prefix, dim in [
        ("toShape", toDim),
        ("toShapeStrides", toDim),
        ("reductionShape", redDim),
        ("reductionShapeStrides", redDim),
    ]:
        for d in range(dim):
            lines.append(f"  let {prefix}{d} = metaBuffer.{prefix}{d};")
    return "\n".join(lines)


def generateDecomposeDim(toDim) -> str:
    if toDim == 0:
        return ""
    lines = ["    var dec_tmp = i;"]
    for d in range(toDim - 1, -1, -1):
        lines.append(f"    let todim{d} = dec_tmp % toShape{d};")
        if d > 0:
            lines.append(f"    dec_tmp = dec_tmp / toShape{d};")
    return "\n".join(lines)


def generateForLoop(toDim, redDim, indent) -> str:
    pad = " " * indent
    if toDim > 0:
        ofs = "+".join([f"todim{d} * toShapeStrides{d}" for d in range(toDim)])
        lines = [f"{pad}let ofs = {ofs};"]
    else:
        lines = [f"{pad}let ofs = 0u;"]
    for d in range(redDim):
        lines.append(
            f"{pad}{'  ' * d}for (var red{d} = 0u; red{d} < reductionShape{d}; "
            f"red{d} = red{d} + 1u) {{"
        )
    inner = pad + "  " * redDim
    if redDim > 0:
        index = "+".join(
            [f"red{d} * reductionShapeStrides{d}" for d in range(redDim)])
        lines.append(f"{inner}v = v + array_x[ofs + {index}];")
    else:
        lines.append(f"{inner}v = v + array_x[ofs];")
    for d in range(redDim - 1, -1, -1):
        lines.append(f"{pad}{'  ' * d}}}")
    return "\n".join(lines)


# CPU実装(sumReduction44まで)に合わせて4次元までの縮約に対応する
MAX_DIM = 4

for t in ["float32", "int32", "uint8", "bool"]:
    scalar_type = DTYPE_TO_SCALAR_TYPE[t]
    for toDim in range(MAX_DIM + 1):
        for redDim in range(MAX_DIM + 1):
            kernel_name = f"sum_{t}_{toDim}_{redDim}"

            source = f"""// Auto-generated by tools/generate_webgputensor_wgsl_reduction_op.py

@group(0) @binding(0) var<storage, read> array_x: array<{scalar_type}>;
@group(0) @binding(1) var<storage, read_write> array_y: array<{scalar_type}>;

struct MetaBuffer {{
{generateMetaMembers(toDim, redDim)}
}}

@group(0) @binding(2) var<storage, read> metaBuffer: MetaBuffer;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {{
  let len = metaBuffer.len;
{generateMetaLoads(toDim, redDim)}
  for (var i = global_id.x; i < len; i = i + 4096u) {{
{generateDecomposeDim(toDim)}

    var v = {scalar_type}(0);
{generateForLoop(toDim, redDim, 4)}
    array_y[i] = v;
  }}
}}
"""
            with open(os.path.join(dst_dir, kernel_name + ".wgsl"), "w") as f:
                f.write(source)
